import { ArrowRight, BookOpen, Clock3, Compass, Flame, Heart, Leaf, Mountain, Orbit, PawPrint, ScrollText, Sparkles } from "lucide-react";
import { assetPath } from "@/lib/assets";
import { duration, number, percent } from "@/lib/format";
import type { GameState } from "@/lib/types";
import { CultivationProgress, GameTimeline, SpiritualRootBadge, StatRow } from "./game-ui";

export function CultivationView({ state, detailed, eta, navigate, onBreakthrough, busy }: { state: GameState; detailed: boolean; eta: number | null; navigate: (view: string) => void; onBreakthrough: () => void; busy: boolean }) {
  const { cultivation, breakthrough } = state;
  return <>
    <div className="page-heading"><div><p className="eyebrow">THANH VÂN SƠN · ĐỘNG PHỦ VÔ DANH</p><h1>{detailed ? "Tĩnh tâm tu luyện" : "Động Phủ"}</h1></div><span className="activity-tag"><span />{state.player.current_activity === "cultivating" ? "Đang tu luyện" : "Đang nghỉ ngơi"}</span></div>
    <div className="home-layout"><div className="main-column">
      <section className="cultivation-scene" aria-label="Động phủ tu luyện" style={{ backgroundImage: `url(${assetPath("maps/qingyun_mountain")})` }}>
        <div className="scene-top"><span><Mountain size={14} /> Linh khí hội tụ</span><span>Thanh tĩnh · Bế quan</span></div>
        <div className="realm-heading"><p>{state.player.name}</p><h2>{state.realm.name}</h2><span className="stage-ornament">TẦNG {state.realm.stage}</span></div>
        <div className="cultivator-art"><div className="cultivation-circle" /><img src={assetPath("characters/player/default")} width={320} height={420} alt="Tu sĩ áo dài ngồi tĩnh tọa giữa núi mây" /></div>
        <p className="scene-verse">Một niệm tĩnh tâm, vạn đạo quy nguyên.</p>
        <div className="scene-progress"><CultivationProgress cultivation={cultivation} /><div className="progress-meta"><span><Sparkles size={14} /> +{number(cultivation.rate_per_minute, 2)} tu vi / phút</span><span><Clock3 size={14} />{eta === 0 ? "Bình cảnh đã tới" : `Còn ${duration(eta)}`}</span></div></div>
      </section>
      <div className="cultivation-actions"><div><Orbit size={20} /><span><strong>{breakthrough.available ? "Bình cảnh đã tới" : "Linh khí đang vận chuyển"}</strong><small>{breakthrough.available ? "Đã đủ tu vi để thử sức với cảnh giới tiếp theo." : "Năm tháng trôi qua, đạo hạnh dần sâu."}</small></span></div>{detailed || breakthrough.available ? <button className={`primary-button ${breakthrough.available ? "breakthrough-ready" : ""}`} onClick={onBreakthrough} disabled={busy || !breakthrough.target}><Flame size={18} />{busy ? "Đang cảm nhận…" : breakthrough.available ? "ĐỘT PHÁ" : "XEM BÌNH CẢNH"}<ArrowRight size={16} /></button> : <button className="primary-button" onClick={() => navigate("cultivation")}><Orbit size={18} />TU LUYỆN<ArrowRight size={16} /></button>}</div>
      {detailed ? <section className="cultivation-details"><div><div className="section-heading"><h2>Vận chuyển linh khí</h2><Leaf size={18} /></div><StatRow label="Cơ sở" value={`+${number(cultivation.base_rate_per_minute, 3)}`} /><StatRow label={state.spiritual_root.name} value={`+${number(cultivation.root_bonus_per_minute, 3)}`} /><StatRow label="Tổng tu vi / phút" value={`+${number(cultivation.rate_per_minute, 3)}`} accent /></div><div><div className="section-heading"><h2>Bình cảnh tiếp theo</h2><Flame size={18} /></div><h3>{breakthrough.target ? `${breakthrough.target.name} · Tầng ${breakthrough.target.stage}` : "Tận cùng tiên lộ"}</h3><StatRow label="Tu vi cần thiết" value={number(breakthrough.required_exp)} /><StatRow label="Trạng thái" value={breakthrough.available ? "Có thể đột phá" : breakthrough.target ? "Đang tích lũy" : "Đã viên mãn"} /></div></section> : <section className="opportunities"><div className="section-heading"><h2>Trên đường vấn đạo</h2><span>Tiên duyên chưa tới</span></div><div className="opportunity-grid">{[{ id: "exploration", icon: Compass, name: "Thám hiểm", text: "Ngoài kia, núi thẳm mây ngàn." }, { id: "skills", icon: BookOpen, name: "Công pháp", text: "Một trang cổ thư, một con đường." }, { id: "alchemy", icon: Flame, name: "Luyện đan", text: "Chờ ngày nhóm lửa đan lô." }].map(item => <a key={item.id} href={`#${item.id}`} onClick={() => navigate(item.id)} className={`opportunity ${item.id}`}><item.icon size={24} /><h3>{item.name}</h3><p>{item.text}</p><span>Chưa mở <ArrowRight size={14} /></span></a>)}</div></section>}
    </div><aside className="context-column">
      <section className="root-section"><div className="section-heading"><h2>Căn nguyên</h2><Sparkles size={17} /></div><SpiritualRootBadge root={state.spiritual_root} /><StatRow label="Tu luyện" value={`×${number(state.spiritual_root.cultivation_modifier, 2)}`} /><StatRow label="Tỷ lệ đột phá" value={`×${number(state.spiritual_root.breakthrough_modifier, 2)}`} /><p className="root-note">Linh căn là khởi điểm.<br />Đạo hạnh nằm ở lòng kiên định.</p></section>
      <section className="companions"><div className="section-heading"><h2>Tiên lộ đồng hành</h2></div><div className="companion-row"><PawPrint size={23} /><span><strong>Linh thú</strong><small>{state.active_pet ?? "Chưa kết khế ước"}</small></span></div><div className="companion-row"><Heart size={23} /><span><strong>Đạo lữ</strong><small>{state.dao_partner ?? "Chưa có người đồng hành"}</small></span></div></section>
      <section className="recent-section"><div className="section-heading"><h2>Tiên ký</h2><ScrollText size={17} /></div><GameTimeline logs={state.recent_logs.slice(0, 4)} /><a href="#journal" onClick={() => navigate("journal")} className="text-link">Xem nhật ký <ArrowRight size={14} /></a></section>
      {detailed && <p className="muted footnote">Cơ hội đột phá hiện tại: {percent(breakthrough.final_chance)}</p>}
    </aside></div>
  </>;
}
